---
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  lit-build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: my-lit-project/
      - run:
          name: Build
          working_directory: my-lit-project/
          command: yarn build

  react-build:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: my-react-app/
      - run:
          name: Build
          working_directory: my-react-app/
          command: yarn build

workflows:
  lit-ci:
    jobs:
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
      - lit-build
  react-ci:
    jobs:
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
      - react-build

