---
version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  lit-lint:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: my-lit-project/
      - run:
          name: Lint with ESLint
          working_directory: my-lit-project/
          command: yarn lint
      - run:
          name: Check formatting using Prettier
          working_directory: my-lit-project/
          command: yarn format:check

  lit-build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: my-lit-project/
      - run:
          name: Build
          working_directory: my-lit-project/
          command: yarn build

  lit-test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: my-lit-project/
      - run:
          name: Test
          working_directory: my-lit-project/
          command: yarn test

  react-build:
    docker:
      - image: cimg/node:16.20
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          app-dir: my-react-app/
      - run:
          name: Build
          working_directory: my-react-app/
          command: yarn build

workflows:
  lit-ci:
    jobs:
      - lit-lint
      - lit-build
      - lit-test:
          requires:
            - lit-build
  react-ci:
    jobs:
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
      - react-build

